# Notify users about breaking change regarding secrets, to not destroy current installations
{{- $deprecated_username := (default (dict) (default (dict) .Values.secrets).st2).username }}
{{- $deprecated_password := (default (dict) (default (dict) .Values.secrets).st2).pasword }}
{{- if or $deprecated_username $deprecated_password }}
{{- fail "Please update your values! Values for username and password moved from secrets.st2.* to st2.*" }}
{{- end }}
{{- if not .Values.st2.existingAuthSecret }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "stackstorm-ha.secrets.st2Auth" . }}
  annotations:
    description: StackStorm username and password, used for basic .htaccess auth
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
spec:
  type: Opaque
  path: {{ .Values.vaultSecrets.stackstorm }}
  keys:
    - ST2_AUTH_USERNAME
    - ST2_AUTH_PASSWORD
    - LDAP_PWD
{{- end }}
