# Notify users about breaking change regarding secrets, to not destroy current installations
{{- $deprecated_crypto_key := (default (dict) (default (dict) .Values.secrets).st2).datastore_crypto_key }}
{{- if $deprecated_crypto_key }}
{{- fail "Please update your values! The datastore_crypto_key value moved from secrets.st2.* to st2.*" }}
{{- else if and (ne "disable" (default "" .Values.st2.datastore_crypto_key)) (not .Values.st2.existingDatastoreSecret) }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  {{- $name := print .Release.Name "-st2-datastore-crypto-key" }}
  name: {{ $name }}
  annotations:
    description: StackStorm crypto key used to encrypt/decrypt KV records
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
spec: 
  type: Opaque
  path: {{ .Values.vaultSecrets.stackstorm }}
  keys:
    - datastore_crypto_key
{{- end }}
