{{- if .Values.rabbitmq.enabled }}
# This configuration is a workaround to https://github.com/bitnami/charts/issues/4635
# This code block should be dropped once the above issue is resolved and definitions can be defined as shown in
# https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Release.Name }}-rabbitmq-definitions
  annotations:
    description: A rabbitmq definition which will be loaded by the rabbitmq subchart to enable mirroring for Rabbit HA
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
spec:
  type: Opaque
  path: {{ .Values.vaultSecrets.rabbitmq }}
  keys:
    - rabbitmq-definitions.json
{{- end }}
