---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Release.Name }}-st2-kv
  annotations:
    description: Key/Value pairs to save in StackStorm's datastore
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
spec:
  type: Opaque
  path: {{ .Values.vaultSecrets.envConfig }}
  keys:
    - st2kv.yaml
