---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Release.Name }}-st2-apikeys
  annotations:
    description: A list of StackStorm API keys with metadata that will be imported into the system
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
spec:
  type: Opaque
  path: {{ .Values.vaultSecrets.stackstorm }}
  keys:
    - apikeys.yaml
