{{- if or (not .Values.auth.existingErlangSecret) (not .Values.auth.existingPasswordSecret) }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: Opaque
  path: {{ .Values.vaultSecrets.rabbitmq }}
  keys:
    - rabbitmq-password
    - rabbitmq-erlang-cookie
{{- end }}
